language: go

go:
  - 1.11.x
  - tip

env:
  global:
    - CC_TEST_REPORTER_ID="1d904046788b6f68a50265a9d1fd89263709d30bd332156ac86ed3e55aca8a37"

before_script:
  # coverage reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -v -race -coverprofile=coverage.out -covermode=atomic

after_script:
  - ./cc-test-reporter format-coverage -t gocov coverage.out
  - ./cc-test-reporter upload-coverage
